language: java

jdk:
  - oraclejdk8

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test

after_success:
  - mvn cobertura:cobertura
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean

cache:
  directories:
    - $HOME/.m2

services:
  - postgresql

before_script:
  - psql -c 'create database coruja;' -U postgres
